name: django-api-portfolio

# Configuraciones de entorno
env:
  - SECRET_KEY=SECRET_KEY
  - DATABASE_URL=DATABASE_URL
  - DEBUG=false

# Comando para iniciar la aplicación
start: gunicorn mysite.wsgi:application -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT

# Configuraciones adicionales para la aplicación de Django
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:$PORT
    ports:
      - $PORT:$PORT
    env:
      - SECRET_KEY=SECRET_KEY
      - DATABASE_URL=DATABASE_URL
      - DEBUG=false
    # Configuraciones de montaje de archivos estáticos y de medios
    volumes:
      - /app/static:/app/mysite/static
      - /app/media:/app/mysite/media
